[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OpenDSSDirect = "a8b11937-1041-50f2-9818-136bb7a8fb06"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
